name       : fcitx-qt5
version    : 1.2.4
release    : 1
source     :
    - https://github.com/fcitx/fcitx-qt5/archive/1.2.4.tar.gz : 55324d93801c1189366519a3888a9703a4f57d32152cfedd68c311413775da72
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : desktop.core
summary    : Qt5 IM Module for Fcitx
description: |
    Qt5 IM Module for Fcitx
builddeps  :
    - pkgconfig(fcitx)
    - pkgconfig(Qt5Core)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
rundeps    :
    - devel: fcitx-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
